---
- name: Enable extra packages for RHEL OS family
  package: name=epel-release
  when: >
    x2goclient_install
    and (ansible_os_family|lower == "redhat" or
     ansible_os_family|lower == "almalinux")
  tags: x2goclient

- name: Install X2Go client
  package: name=x2goclient
  when: x2goclient_install
  tags: x2goclient

- name: Uninstall X2Go client
  package: name=x2goclient
  when: not x2goclient_install
  tags: x2goclient
