---
- name: Enable extra packages for RHEL OS family
  package: name=epel-release
  when: |
    ansible_pkg_mgr == "dnf"
    and x2goclient_state != "absent"
  tags: x2goclient

- name: Make X2Go client {{ x2goclient_state }}
  package: name=x2goclient
  state: "{{ x2goclient_state }}"
  tags: x2goclient
